### ISSUE TITLE
ListSaver per backend user

### ISSUE THREAD

**Issue by apinard** [sixgweb/listsaver-plugin#1]
Hi,

First of all, awesome plugin !! very useful. Should be promoted more (talk.octobercms.com / slack).. thank you.

Alright so now, the only thing is that in my application, I have many users and each of them needs to have their own lists...

Could you please fire an event in these functions (in the filterwidgets\ListSaver.php) : getListSaverPreferences() and  onSaveListSaverPreference()

------

Right now, I can extend the table 'sixgweb_listsaver_preferences' adding a 'created_by_user_id' field. 

I also extend the model in my Plugin.php to add 'created_by_user_id'.

I have modified the two functions above in filterwidgets\ListSaver.php - which is not good - this is why it would be good to have an event...

`public function onSaveListSaverPreference()
    {
        if (!\BackendAuth::userHasAccess('sixgweb.listsaver.manage')) {
            return;
        }

       ...
       
        $preference = Preference::create([
            'name' => $name,
            'list' => $list,
            'filter' => $filter,
            'namespace' => $this->getPreferenceNamespace(),
            'group' => $this->getPreferenceGroup(),
            'blueprint_uuid' => $this->controller->vars['activeSource']->uuid ?? null,
            <NEW>                        'created_by_user_id' => \BackendAuth::getUser()->id,                      </NEW>
        ]);

      ..

        return [
            '#' . $scope->getId('group') => $this->listFilterWidget->makePartial('scope', ['scope' => $scope]),
            'closePopover' => true,
        ];
    }`
    
    and 
    
    `protected function getListSaverPreferences()
    {
        return Preference::where('namespace', $this->getPreferenceNamespace())
            ->where('group', $this->getPreferenceGroup())
            ->where(function ($query) {
                if (isset($this->controller->vars['activeSource']->uuid)) {
                    $query->where('blueprint_uuid', $this->controller->vars['activeSource']->uuid);
                } else {
                    $query->whereNull('blueprint_uuid');
                }
            })
            <NEW>                     ->where('created_by_user_id', \BackendAuth::getUser()->id)              </NEW>
            ->lists('name', 'id');
    }`

**Comment by sixgweb** [comment]
Glad you find it useful! I've put in a few extra features in version 1.0.9.  Preference model now saves the backend_user_id and has an is_private column, which defaults to 1.  If you don't want list sharing, you can disable it in Settings->ListSaver.  If you enable it, you can control who can create public lists in the role permissions.

I've added a new event, should you want to manipulate the get query.  Of course, you can use [Model Events](https://docs.octobercms.com/3.x/extend/system/models.html#model-events) to manipulate the data before creating/saving.

**Comment by apinard** [comment]
Great, thank you !!
