### ISSUE TITLE
[Feature] - not an issue!! - Specific records in a list 

### ISSUE THREAD

**Issue by apinard** [sixgweb/listsaver-plugin#4]
Hi,

Thanks again for this plugin!! very useful. The proof, I received a request from a user. Here is the feature requested... :

The person said that he would like to be able to, after he applied filters, that the list kept only the selected records. 

For example, with the october/test plugin:

![image](https://github.com/sixgweb/listsaver-plugin/assets/97567768/7de593dd-a52f-4c8b-ad35-ee1a14e7721a)

**Comment by sixgweb** [comment]
Hi there!  I'm thinking this is a bit of scope creep for ListSaver.  Why not create a "favorites" column and add it to the current filter widget?  Perhaps a bulk "Add Checked to Favorites" or an inline switch to toggle each item as a favorite?  Your user can then check the Favorites filter and save the list to ListSaver.

**Comment by apinard** [comment]
Or when a list is created, all rows that are checked are stored (ids) as well with the current filters configuration. And perhaps, the plugin could listen to [backend.list.extendQuery] as if there is any id's stored, do a whereIn[]. 

this would just allow to create really customized list. (regardless if filters have been used).

**Comment by sixgweb** [comment]
Yep, that's the solution I considered when you made the feature request.  Storing the checked IDs is easy enough and has been added to [1.0.19](https://github.com/sixgweb/listsaver-plugin/releases/tag/1.0.19).

What to do with the checked IDs is outside the scope of ListSaver.  Some may want to query whereIn(), some may want to query whereNotIn(), some may want to keep the checked state alongside the unchecked, etc.

I've added a new event [sixgweb.listsaver.applyScopeToQuery](https://sixgweb.github.io/oc-plugin-documentation/listsaver/events.html#applyscopetoquery) that developers can use to manipulate the list query with the checked values.

**Comment by apinard** [comment]
"What to do with the checked IDs is outside the scope of ListSaver. Some may want to query whereIn(), some may want to query whereNotIn(), some may want to keep the checked state alongside the unchecked, etc."

Totally agree, thank you!! can't wait to test.

**Comment by apinard** [comment]
Just an headsup, it works well! thank you again @sixgweb , very appreciated.
