### ISSUE TITLE
OC 3.7.4 - Error and placement

### ISSUE THREAD

**Issue by apinard** [sixgweb/listsaver-plugin#5]
Hi,

I updated OctoberCMS to version 3.7.4 and two issues with the ListSaver now;

- When I click on the ListSaver, an error comes up:

"Form behavior does not contain a field for ':field'." on line 457 of ...installation...\modules\backend\widgets\Filter.php"

- The placement -> it's now right after the last filter

![image](https://github.com/user-attachments/assets/562dcaa9-3c32-4791-a074-e8aacd1278d1)

**Comment by sixgweb** [comment]
Hi,

Please  update to 1.0.22 for the fix and let me know if you have any other issues.

**Comment by apinard** [comment]
For what I stated above, it is fixed. 

Thank you.
